---
- hosts: webservers
  sudo: true
  user: root
  tasks:
    - name: Install Apache, MySQL, PHP
      yum: pkg={{ item }} state=installed
      with_items:
        - httpd
        - mysql
        - mysql-server
        - php
        - php-common
        - php-gd
        - php-mysql
        - php-pear
        - php-xml
        - MySQL-python
      notify:
        - httpd restarted
        - mysqld restarted
    - name: be sure mysqld is running and enabled
      service: name=mysqld state=started enabled=yes
    - name: Create MySQL database
      mysql_db: db=mydb encoding=utf8 state=present
    - name: Create MySQL user
      mysql_user: name=user password=password priv=mydb.*:ALL state=present
  handlers:
    - name: httpd restarted
      service: name=httpd enabled=yes state=restarted
    - name: mysqld restarted
      service: name=mysqld enabled=yes state=restarted
